export const surpriseMePrompts = [
  'an armchair designed like a sliced watermelon with realistic texture, 3D render',
  'a surrealist dreamscape oil painting by Salvador Dalí featuring a cat floating among melting clocks',
  'teddy bears enjoying sushi at a night market in Tokyo, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess with a wise owl',
  'a panda mad scientist in a steampunk lab, mixing glowing neon liquids, digital art',
  "a macro 35mm photograph of two hamsters in Hawaii, each wearing sunglasses and sipping tiny coconut drinks, digital art",
  '3D render of a bioluminescent jellyfish floating in a deep-sea aquarium on a dark background, digital art',
  'an astronaut sipping coffee at a retro diner on the Moon, vaporwave aesthetic',
  'an oil painting portrait of a capybara dressed as a Victorian-era noble, with a regal cane and monocle',
  'a stained glass window depicting a cosmic nebula with vibrant swirling colors',
  'a pencil and watercolor drawing of a futuristic city with floating gardens and self-driving bicycles',
  'a sunlit indoor lounge area featuring a cascading waterfall and a pool with shimmering bioluminescent fish, digital art',
  'a fortune-telling shiba inu reading tarot cards inside a floating teacup, digital art',
  '"A Sea Otter with a Pearl Earring" reimagined as a cyberpunk hologram, digital painting',
  'an oil pastel drawing of a grumpy cat navigating a spaceship through an asteroid field',
  'a painting of a phoenix rising in the style of Van Gogh’s Starry Night',
  'a bowl of ramen with a miniature dragon coiled inside, its breath forming the steam, digital illustration',
  'a plush toy robot sitting against a yellow wall, reading a tiny book',
  'a synthwave-style neon pyramid reflecting in a tranquil lake at night, digital art',
  'two futuristic skyscrapers connected by a glowing energy bridge, digital art',
  'a 3D render of a hot air balloon shaped like a galaxy, floating above an alien landscape',
  'a comic book cover of a superhero with lightning powers wearing futuristic armor',
  'a dynamic explosion of holographic powder on a pitch-black background',
  'a photo of a Samoyed dog wearing a tiny backpack, hiking with a Siamese cat',
  'a yeti wearing a tuxedo, standing confidently in a lavish purple ballroom',
  "a photo of Michelangelo’s sculpture of David wearing futuristic VR goggles",
  'a cyberpunk samurai riding a neon-lit robotic horse on Mars, lomography',
  'a sleek, modern electric sports car racing along a neon-lit cyber highway, 50mm photography',
  'a hyper-realistic portrait of a woman with galaxy-patterned hair and glowing violet eyes',
  'a man stepping through a shimmering portal into an alternate 1920s steampunk universe',
  'SpongeBob SquarePants in a noir detective thriller, standing in a rainy alleyway',
  'a velociraptor in a suit and tie, serving customers at a high-end restaurant, lomography',
  'a cyberpunk wanderer navigating the neon-soaked streets of Kowloon at midnight, 50mm lens',
  'a sentient BBQ grill with a mischievous smile, preparing food in the style of a Pixar animated movie',
  'a futuristic nightclub filled with dancing holographic cyborgs under pulsating neon lights',
  'a retro 1980s anime version of a lost Star Wars episode, complete with hand-drawn action scenes',
  'a gourmet burger floating in space, with Saturn’s rings as the bun, professional food photography',
  'a synthwave-style hedgehog with a cybernetic mohawk, standing on a futuristic rooftop, Blade Runner aesthetic',
  'an astronaut making first contact with an extraterrestrial jellyfish, realistic photography',
  'a dinosaur exploring an abandoned futuristic city covered in lush jungle, cinematic photography',
  'a man falling in love with an AI hologram, digital painting',
  'a photo of a cyberpunk detective investigating a mystery in the neon-lit streets of Tokyo, lomography',
  'Dracula walking casually down a 1920s New York street, sipping from a blood-red cocktail, black and white photography',
  'a synthwave-styled jet soaring above a glowing cyber-city at sunset',
  'a man lost in a futuristic Tokyo where holograms blend with reality, heavy rain and neon reflections, 50mm',
  'a space shuttle gliding above a futuristic Cape Town skyline, digital painting',
  'a mechanical hummingbird made of stained glass and gears, hovering over a glowing flower, steampunk',
];
